In [6]:
import numpy as np
import random
import networkx as nx

In [4]:
no_vertices = 20
no_steps = 10000
i=0
opinions = np.random.randint(-1,2,size=no_vertices,dtype='int')
print(opinions)
clock = np.random.exponential(scale = 1.0, size=no_vertices)
while i < no_steps:
    vertex_ind = np.argmin(clock)
    neighbour_ind = random.randint(0,no_vertices - 1)
    while neighbour_ind == vertex_ind:
        neighbour_ind = random.randint(0,no_vertices - 1)
    if not abs(opinions[vertex_ind] - opinions[neighbour_ind]) == 2:
       opinions[vertex_ind] = opinions[neighbour_ind]
    clock = clock - clock[np.argmin(clock)]
    clock[vertex_ind] = np.random.exponential(scale = 1.0, size=1)
    i=i+1
print(opinions)

[ 1  1 -1  0  0  1  0  1  1 -1  0  0 -1  0  0  1  0  0  0  1]
[-1 -1 -1  1 -1  1 -1  1 -1 -1 -1  1 -1  1 -1 -1 -1 -1  1 -1]


In [13]:
no_vertices = 3
no_steps = 100000
no_features = 3
no_opinions=2

opinions = np.random.randint(0,no_opinions,size=[no_vertices,no_features],dtype='int')
print(opinions)
# opinions[vertex number][feature number]
clock = np.random.exponential(scale = 1.0, size=no_vertices)
i=0
while i < no_steps:
    vertex_ind = np.argmin(clock)
    agreements = np.zeros(no_vertices)
    n=0
    while n < no_vertices:
        k=0
        while k < no_features:
            if opinions[vertex_ind][k]==opinions[n][k]:
                agreements[n] = agreements[n] + 1
            k=k+1
        n=n+1
    agreements[vertex_ind] = 0 #agreements[vertex_ind] - no_features
    s=np.sum(agreements)
    agreements = agreements / s
    l=0
    while l < no_vertices-1:
        agreements[l+1] = agreements[l+1] + agreements[l]
        l=l+1
    r = random.random()
    l=0
    while l<no_vertices - 1:
        if r < agreements[l]:
            neighbour_ind = l
            break
        l=l+1
    ch_feature = random.randint(0, no_features-1)
    l=0
    while True:
        if np.all(opinions[vertex_ind] == opinions[neighbour_ind]):
            break
        if not opinions[vertex_ind][ch_feature] == opinions[neighbour_ind][ch_feature]:
            opinions[vertex_ind][ch_feature] = opinions[neighbour_ind][ch_feature]
            break
        else:
            k=ch_feature
            ch_feature = random.randint(0, no_features-1)
    i=i+1
print(opinions)

[[0 1 0]
 [1 1 1]
 [0 1 0]]
[[1 1 1]
 [1 1 1]
 [0 1 0]]


In [7]:
no_vertices = 20
no_steps = 10000
G=nx.erdos_renyi_graph(no_vertices,0.5)
opinions = np.random.randint(-1,2,size=no_vertices,dtype='int')
print(opinions)
clock = np.random.exponential(scale = 1.0, size=no_vertices)
i=0
while i < no_steps:
    vertex_ind = np.argmin(clock)
    neighbours=list(G.neighbors(vertex_ind))
    neighbour_ind = random.choice(neighbours)
    if not abs(opinions[vertex_ind] - opinions[neighbour_ind]) == 2:
        opinions[vertex_ind] = opinions[neighbour_ind]
    clock = clock - clock[np.argmin(clock)]
    clock[vertex_ind] = np.random.exponential(scale = 1.0, size=1)
    i=i+1
print(opinions)

[ 0  1  0  1  1 -1  1 -1  0  0 -1 -1  1  0 -1  0 -1  1 -1  0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [8]:
no_vertices = 3
no_steps = 100000
no_features = 3
no_opinions=2
G=nx.complete_graph(no_vertices)

opinions = np.random.randint(0,no_opinions,size=[no_vertices,no_features],dtype='int')
print(opinions)
# opinions[vertex number][feature number]
clock = np.random.exponential(scale = 1.0, size=no_vertices)
i=0
while i < no_steps:
    vertex_ind = np.argmin(clock)
    agreements = np.zeros(no_vertices)
    n=0
    neighbors=list(G.neighbors(vertex_ind))
    for n in neighbors:
        k=0
        while k < no_features:
            if opinions[vertex_ind][k]==opinions[n][k]:
                agreements[n] = agreements[n] + 1
            k=k+1
        n=n+1
    agreements[vertex_ind] = 0 #agreements[vertex_ind] - no_features
    s=np.sum(agreements)
    agreements = agreements / s
    l=0
    while l < no_vertices-1:
        agreements[l+1] = agreements[l+1] + agreements[l]
        l=l+1
    r = random.random()
    l=0
    while l<no_vertices - 1:
        if r < agreements[l]:
            neighbour_ind = l
            break
        l=l+1
    ch_feature = random.randint(0, no_features-1)
    l=0
    while True:
        if np.all(opinions[vertex_ind] == opinions[neighbour_ind]):
            break
        if not opinions[vertex_ind][ch_feature] == opinions[neighbour_ind][ch_feature]:
            opinions[vertex_ind][ch_feature] = opinions[neighbour_ind][ch_feature]
            break
        else:
            k=ch_feature
            ch_feature = random.randint(0, no_features-1)
    i=i+1
print(opinions)

[[1 0 0]
 [0 0 0]
 [0 0 1]]
[[1 0 0]
 [0 0 0]
 [1 0 0]]
